spring:
  profiles:
    active: qa


---
spring:
  profiles: dev

server:
  port: 9090

default:
  course:
    name: SAP HANA
    chapterCount: 3

course:
  name: AWS, AZURE and CLOUDFLARE
  chapterCount: 40
  rating: 5
  author: Anonymous


---
spring:
  profiles: qa

server:
  port: 9091

default:
  course:
    name: SAP os
    chapterCount: 3_

course:
  name: AWS, DOCKER and Angular
  chapterCount: 450
  rating: 50
  author: Bhupendra_s